import Head from "next/head";
import Image from "next/image";
import { apiClient } from "../lib/apiClient";
import styles from "../styles/Home.module.css";

export default function Home({ contents }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <ul>
          {contents.map((content) => {
            return <li key={content.id}>{content.title}</li>;
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getStaticProps = async (context) => {
  const draftKey = context.previewData?.draftKey;
  console.log(draftKey);

  const contents = await apiClient.getList({
    endpoint: "games",
    draftKey: draftKey,
  });
  console.log(contents);

  return {
    props: {
      contents: contents.contents,
    },
  };
};
